name: Build & Publish Debug APK

on:
 push:
  branches:
   - master
 workflow_dispatch:
   
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup venv
        run: python -m venv venv
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Add local.properties
        run: touch local.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Add Keystore
        env:
          LOCAL_PROPERTIES: ${{ secrets.SIGN_KEYSTORE }}
        run: echo -n "$LOCAL_PROPERTIES" | base64 -d > ../keystore.jks
      - name: Test Keystone
        run: md5sum ../keystore.jks
      #- name: Test Keystore
      #  env:
      #    RELEASE_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
      #  run: keytool -list -storepass "$RELEASE_STORE_PASSWORD" -keystore ../keystore.jks
      - name: Add SigningConfig
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
        run: |
          printf "releaseStoreFile=$(realpath $PWD/../keystore.jks)\nRELEASE_STORE_PASSWORD=%s\nRELEASE_KEY_ALIAS=%s\nRELEASE_KEY_PASSWORD=%s" \
          $RELEASE_STORE_PASSWORD \
          $RELEASE_KEY_ALIAS \
          $RELEASE_KEY_PASSWORD \
          > ~/.gradle/gradle.properties
      - name: Build APK release
        run: ./gradlew assembleRelease --stacktrace
      - name: Build APK release
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: apkDebug
          path: app/build/outputs/apk/debug/BoFiLo*.apk
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: apkRelease
          path: app/build/outputs/apk/release/BoFiLo*.apk
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK Debug from build
        uses: actions/download-artifact@v4
        with:
          name: apkDebug
      - name: Download APK Release from build
        uses: actions/download-artifact@v4
        with:
          name: apkRelease
      - name: Generate release tag
        id: tag
        run: echo "release_tag=CIBuild_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
      - name: Find files
        run: find -name "*.apk"
      - name: Upload Debug and Release APK
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          name: PreRelease
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ./BoFiLo_*.apk
          prerelease: true
          generate_release_notes: true
